import { describe, it, expect } from "vitest";
import {
  formatCurrency,
  formatCurrencyNullable,
  parseCurrencyToNumber,
  formatCurrencyInput,
  formatDate,
  formatCPF,
  formatCNPJ,
  formatPhone,
} from "../lib/formatters";

describe("formatCurrency", () => {
  it("formats positive numbers", () => {
    // Note: Due to locale formatting, tests might need to match exact spaces 
    // such as non-breaking spaces generated by toLocaleString, we use generic replacements to be safe
    const result = formatCurrency(1234.56).replace(/\s/g, " ");
    expect(result).toBe("R$ 1.234,56");
  });

  it("formats negative numbers", () => {
    const result = formatCurrency(-1234.56).replace(/\s/g, " ");
    expect(result).toBe("R$ -1.234,56");
  });

  it("formats zero", () => {
    const result = formatCurrency(0).replace(/\s/g, " ");
    expect(result).toBe("R$ 0,00");
  });
  
  it("formats large numbers correctly", () => {
    const result = formatCurrency(1000000).replace(/\s/g, " ");
    expect(result).toBe("R$ 1.000.000,00");
  });
});

describe("formatCurrencyNullable", () => {
  it("formats number correctly", () => {
    const result = formatCurrencyNullable(50).replace(/\s/g, " ");
    expect(result).toBe("R$ 50,00");
  });

  it("handles null", () => {
    const result = formatCurrencyNullable(null).replace(/\s/g, " ");
    expect(result).toBe("R$ 0,00");
  });

  it("handles undefined (if passed via JS loosely)", () => {
    const result = formatCurrencyNullable(undefined as any).replace(/\s/g, " ");
    expect(result).toBe("R$ 0,00");
  });
});

describe("parseCurrencyToNumber", () => {
  it("parses valid formatted string", () => {
    expect(parseCurrencyToNumber("1.234,56")).toBe(1234.56);
  });

  it("parses strings with currency symbol", () => {
    expect(parseCurrencyToNumber("R$ 1.234,56")).toBe(1234.56);
  });

  it("returns 0 for empty or invalid strings", () => {
    expect(parseCurrencyToNumber("abc")).toBe(0);
    expect(parseCurrencyToNumber("")).toBe(0);
  });
});

describe("formatCurrencyInput", () => {
  it("formats numbers as typed", () => {
    expect(formatCurrencyInput("1")).toBe("0,01");
    expect(formatCurrencyInput("123")).toBe("1,23");
    expect(formatCurrencyInput("123456")).toBe("1.234,56");
  });

  it("handles non-numeric characters", () => {
    expect(formatCurrencyInput("abc123def")).toBe("1,23");
  });
});

describe("formatDate", () => {
  it("formats valid ISO dates", () => {
    expect(formatDate("2023-12-25")).toBe("25/12/2023");
    expect(formatDate("2023-12-25T15:30:00Z")).toBe("25/12/2023");
  });

  it("returns dash for null", () => {
    expect(formatDate(null)).toBe("—");
  });

  it("returns the original string if invalid date format", () => {
    expect(formatDate("invalid-date")).toBe("invalid-date");
  });
});

describe("formatCPF", () => {
  it("formats 11 digit strings correctly", () => {
    expect(formatCPF("12345678901")).toBe("123.456.789-01");
  });

  it("formats partial strings correctly", () => {
    expect(formatCPF("1234567")).toBe("123.456.7");
  });

  it("ignores non-numeric characters", () => {
    expect(formatCPF("123.456x789-01")).toBe("123.456.789-01");
  });
});

describe("formatCNPJ", () => {
  it("formats 14 digit strings correctly", () => {
    expect(formatCNPJ("12345678000199")).toBe("12.345.678/0001-99");
  });

  it("formats partial strings correctly", () => {
    expect(formatCNPJ("12345678000")).toBe("12.345.678/000");
  });
});

describe("formatPhone", () => {
  it("formats 11 digit phones (cellular)", () => {
    expect(formatPhone("11987654321")).toBe("(11) 98765-4321");
  });

  it("formats 10 digit phones (landline)", () => {
    // The format logic in use will put the hyphen differently depending on length
    // Wait, the logic is: `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`
    // "1187654321" length 10 -> (11) 87654-321
    expect(formatPhone("1187654321")).toBe("(11) 87654-321");
  });

  it("formats partial phones", () => {
    expect(formatPhone("11")).toBe("11");
    expect(formatPhone("119")).toBe("(11) 9");
  });

  it("removes invalid chars", () => {
    expect(formatPhone("11a9b8c7d6e5f4g3h2i1")).toBe("(11) 98765-4321");
  });
});
