
-- Email templates table
CREATE TABLE public.email_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE,
  assunto TEXT NOT NULL,
  corpo_html TEXT NOT NULL,
  categoria TEXT NOT NULL DEFAULT 'geral',
  variaveis TEXT[] DEFAULT '{}',
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Emails enviados table
CREATE TABLE public.emails_enviados (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  template_id UUID REFERENCES public.email_templates(id),
  destinatario TEXT NOT NULL,
  assunto TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'enviado',
  erro TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emails_enviados ENABLE ROW LEVEL SECURITY;

-- RLS policies - authenticated users can read templates
CREATE POLICY "Authenticated users can read email_templates"
  ON public.email_templates FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins can manage email_templates"
  ON public.email_templates FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Authenticated users can read emails_enviados"
  ON public.emails_enviados FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert emails_enviados"
  ON public.emails_enviados FOR INSERT TO authenticated WITH CHECK (true);

-- Seed default templates
INSERT INTO public.email_templates (nome, assunto, corpo_html, categoria, variaveis) VALUES
('boas_vindas', 'Bem-vindo(a) à {{empresa}}!', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#f97316,#ea580c);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Bem-vindo(a)! 🎉</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">É um prazer ter você conosco na <strong>{{empresa}}</strong>! Estamos muito felizes com a sua chegada.</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 24px">Se tiver qualquer dúvida, estamos à disposição.</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'boas_vindas', ARRAY['nome', 'empresa', 'email']),

('confirmacao_matricula', 'Matrícula confirmada — {{produto}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#16a34a,#15803d);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Matrícula Confirmada ✅</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Sua matrícula no produto <strong>{{produto}}</strong> foi confirmada com sucesso!</p><table width="100%" style="background:#f8f9fa;border-radius:6px;padding:16px;margin:0 0 24px"><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Produto:</strong> {{produto}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Valor:</strong> R$ {{valor}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Início:</strong> {{data_inicio}}</td></tr></table><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'matricula', ARRAY['nome', 'produto', 'valor', 'data_inicio', 'empresa']),

('lembrete_pagamento', 'Lembrete: pagamento próximo do vencimento', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#eab308,#ca8a04);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Lembrete de Pagamento ⏰</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Este é um lembrete amigável sobre o seu pagamento que vence em breve.</p><table width="100%" style="background:#fffbeb;border-radius:6px;padding:16px;margin:0 0 24px;border-left:4px solid #eab308"><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Valor:</strong> R$ {{valor}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Vencimento:</strong> {{data_vencimento}}</td></tr></table><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'cobranca', ARRAY['nome', 'valor', 'data_vencimento', 'empresa']),

('pagamento_vencido', 'Pagamento vencido — ação necessária', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#dc2626,#b91c1c);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Pagamento Vencido ⚠️</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Identificamos que o pagamento abaixo está vencido. Por favor, regularize para evitar pendências.</p><table width="100%" style="background:#fef2f2;border-radius:6px;padding:16px;margin:0 0 24px;border-left:4px solid #dc2626"><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Valor:</strong> R$ {{valor}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Vencimento:</strong> {{data_vencimento}}</td></tr></table><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'cobranca', ARRAY['nome', 'valor', 'data_vencimento', 'empresa']),

('recibo_pagamento', 'Recibo: pagamento confirmado', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#16a34a,#15803d);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Pagamento Confirmado 💚</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Confirmamos o recebimento do seu pagamento. Obrigado!</p><table width="100%" style="background:#f0fdf4;border-radius:6px;padding:16px;margin:0 0 24px;border-left:4px solid #16a34a"><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Valor pago:</strong> R$ {{valor}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Data:</strong> {{data_pagamento}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Forma:</strong> {{forma_pagamento}}</td></tr></table><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'pagamento', ARRAY['nome', 'valor', 'data_pagamento', 'forma_pagamento', 'empresa']),

('lembrete_sessao', 'Lembrete: sessão agendada', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#2563eb,#1d4ed8);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Sessão Agendada 📅</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Este é um lembrete da sua sessão agendada com <strong>{{profissional}}</strong>.</p><table width="100%" style="background:#eff6ff;border-radius:6px;padding:16px;margin:0 0 24px;border-left:4px solid #2563eb"><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Profissional:</strong> {{profissional}}</td></tr><tr><td style="color:#555;font-size:14px;padding:4px 0"><strong>Sessão:</strong> {{sessao_numero}} de {{total_sessoes}}</td></tr></table><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Abraços,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'sessao', ARRAY['nome', 'profissional', 'sessao_numero', 'total_sessoes', 'empresa']),

('aniversario', 'Feliz Aniversário, {{nome}}! 🎂', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f7;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:linear-gradient(135deg,#a855f7,#7c3aed);padding:32px 40px;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">Feliz Aniversário! 🎂🎉</h1></td></tr><tr><td style="padding:32px 40px"><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px">Olá <strong>{{nome}}</strong>,</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 16px">Hoje é um dia muito especial e queremos te desejar um Feliz Aniversário! 🎈</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 24px">Que este novo ano seja repleto de conquistas, saúde e muita alegria!</p><p style="color:#555;font-size:15px;line-height:1.6;margin:0">Com carinho,<br><strong>Equipe {{empresa}}</strong></p></td></tr><tr><td style="background:#f8f9fa;padding:20px 40px;text-align:center"><p style="color:#999;font-size:12px;margin:0">{{empresa}} — Este é um email automático.</p></td></tr></table></td></tr></table></body></html>', 'aniversario', ARRAY['nome', 'empresa']);

-- Updated at trigger
CREATE TRIGGER update_email_templates_updated_at
  BEFORE UPDATE ON public.email_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
